### PR TITLE
Integrate upstream changes to template

### PR DESCRIPTION
**Pull request by jpaquim**
The upstream Sapper template has been updated to reflect Svelte 3, this PR integrates all the upstream commits.

### CODE REVIEW

**Comment by jpaquim** [comment]
@CompuIves

**Comment by jpaquim** [comment]
@CompuIves any chance of merging this?

**Comment by CompuIves** [comment]
Yep! I'm sorry for the delay!

**Comment by CompuIves** [comment]
Thanks for the fixes!!

**Comment by jpaquim** [comment]
Great! Thank you 😄

**Pull request merged**
